
{
    "room": "Fox Den",
    "author": "Foxifly",
    "css": "https://theme.foxifly.net/rcs/FoxDen_byFoxifly.css",
    "icon": "https://theme.foxifly.net/images/MiniFoxFullLogo_ByFoxifly.png",
    "images": {
        "background":"https://theme.foxifly.net/images/FoxDenBG_ByFoxifly.png",
        "playback": "https://theme.foxifly.net/images/FoxDenPlayback_ByFoxifly.png",
        "host": "https://theme.foxifly.net/images/MiniFoxLogo_ByFoxifly.png",
        "cohost": "https://theme.foxifly.net/images/CoHostImg_ByFoxifly.png"
    },

    "rules": {
        "allowAutorespond": true,
        "allowAutowoot": true,
        "allowAutojoin": false,
        "allowAutograb": true,
        "allowSmartVote": true,
        "allowEmotes": true,
        "allowShowingMehs": true,
        "forceSmartVote": false
    },
    "ccc": {
        "admin": "#FF3E3E",
        "ambassador": "#FF6363",
        "host": "#FFEB44",
        "cohost": "#FFD244",
        "manager": "#FFB044",
        "bouncer": "#FF8D44",
        "rdj": "#FF6300",

        "user": "#C0C0C0"
    },
    "emotes": {
        "foxden1": "https://theme.foxifly.net/images/foxdenmini.png",
        "foxden2": "https://theme.foxifly.net/images/miniminilogo.png",
        "fince1":  "https://theme.foxifly.net/images/aedi1.png",
        "fince2":"https://theme.foxifly.net/images/aedi2.png",
        "fince3":"https://theme.foxifly.net/images/aedi3.png",
        "fince4":"https://theme.foxifly.net/images/aedi4.png",
        "fince5":"https://theme.foxifly.net/images/aedi5.png",
        "fince6":"https://theme.foxifly.net/images/aedi6.png",
        "fin":"https://theme.foxifly.net/images/aed.png",
        "aedi":"https://theme.foxifly.net/images/fince.png"
    },
     "autocomplete": {
         "!commands": 0,
         "!dc": 0,
         "!complaintrain": 0,
         "!train":0,
         "!rules": 0,
         "!faq": 0,
         "!staffapp": 0,
         "!rdjapp": 0,
         "!lothelp": 0,
         "!ping": 0,
         "!pinggif": 0,
         "!source": 0,
         "!facebook": 0,
         "!twitter": 0,
         "!discord": 0,
         "!contact": 0,
         "!blacklist": 0,
         "!website": 0,
         "!link": 0,
         "!urban": 0,
         "!lottery": 0,
         "!enter": 0,
         "!8ball": 0,
         "!fox": 0,
         "!trump": 0,
         "!cat": 0,
         "!gif": 0,
         "!hue": 0,
         "!thonk": 0,
         "!shot": 0,
         "!candy": 0,
         "!hug": 0,
         "!aww": 0,
         "!cookie": 0,
         "!newspaper": 0,
         "!dealwithit": 0,
         "!nope": 0,
         "!satisfy": 0,
         "!love": 0,
         "!stupidfox": 0,
         "!avatar": 0,
         "!fastfood": 0,
         "!entry": 2,
         "!msg": 2,
         "!users": 0,
         "!skip": 2,
         "!skiptro": 2,
         "!lockskip": 2,
         "!add": 2,
         "!remove": 2,
         "!move": 2,
         "!lock": 2,
         "!unlock": 2,
         "!kick": 2,
         "!ban": 2,
         "!unban": 2,
         "!giveaway start": 0,
         "!gstatus": 0,
         "!bl": 2,
         "!settings": 2,
         "!toggle ads": 2,
         "!toggle lottery": 2,
         "!toggle autowoot": 2,
         "!toggle timeguard": 2,
         "!toggle magnetic": 2,
         "!toggle welcome": 2,
         "!toggle history": 2,
         "!toggle urban": 2,
         "!toggle genreguard": 2,
         "!translate": 2,
         "!french": 2,
         "!spanish": 2,
         "!portuguese": 2,
         "!dutch": 2,
         "!mute": 2,
         "!unmute": 2,
         "!userid": 3,
         "!oldmute": 3,
         "!oldunmute": 3,
         "!clearchat": 3,
         "!msg": 3,
         "!troll": 3,
         "!clearwl": 3,
         "!motd": 3,
         "!motd clear": 3,
         "!motd off": 3,
         "!cooldown": 3,
         "!shutdown": 3,
         "!reload": 3,
         "!uptime": 3,
         "!status": 3,
         "!dropzone": 3,
         "!swap": 3,
         "!eval": 3


     }
}
