
{
    "room": "Mineplex Official",
    "author": "baseballboyg/Gavin",
    "css": "https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/mineplex.css",
    "icon": "https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/icon.png",
    "images": {
        "background":"https://cdn.radiant.dj/rcs/bg/2k14minecraft.jpg",
        "playback": "https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/playback.png",
        "host": "https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/fire.png",
        "cohost": "https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/hosts.png"
    },

    "rules": {
        "allowAutorespond": true,
        "allowAutowoot": true,
        "allowAutojoin": true,
        "allowAutograb": true,
        "allowSmartVote": true,
        "allowEmotes": true,
        "allowShowingMehs": true,
        "forceSmartVote": false
    },
    "ccc": {
      "admin":                "#42A5DC",
      "ambassador":           "#84B423",
      "host":                 "#8E0000",
      "cohost":               "#B20000",
      "manager":              "#C11B17",
      "bouncer":              "#FF6A00",
      "rdj":                  "#0068B2",
      "subscriber":           null,
      "silversubscriber":     null,
      "friend":               "#90AD2F",
      "user":                 "#8B92A3"
    },
    "emotes": {
        "eternal": "https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/eternal.png",
        "hero": "https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/hero.png",
        "legend":  "https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/legend.png",
        "potato": "https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/minecraft_potato.gif",
        "mineplex_symbol": "https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/mineplex_symbol.png",
        "mineplex":"https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/mineplex.png",
        "nyan_chiss":"https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/nyan_chiss.png",
        "titan":"https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/titan.png",
        "ultra":"https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/ultra.png",
        "chiss":"https://raw.githubusercontent.com/baseballboyg/MineplexTesting/master/chiss.png"
      },
       "autocomplete": {
           "!commands": 0,
           "!dc": 0,
           "!complaintrain": 0,
           "!train":0,
           "!rules": 0,
           "!faq": 0,
           "!staffapp": 0,
           "!rdjapp": 0,
           "!lothelp": 0,
           "!ping": 0,
           "!pinggif": 0,
           "!source": 0,
           "!facebook": 0,
           "!twitter": 0,
           "!discord": 0,
           "!contact": 0,
           "!blacklist": 0,
           "!website": 0,
           "!link": 0,
           "!urban": 0,
           "!lottery": 0,
           "!enter": 0,
           "!8ball": 0,
           "!fox": 0,
           "!trump": 0,
           "!cat": 0,
           "!gif": 0,
           "!hue": 0,
           "!thonk": 0,
           "!shot": 0,
           "!candy": 0,
           "!hug": 0,
           "!aww": 0,
           "!cookie": 0,
           "!newspaper": 0,
           "!dealwithit": 0,
           "!nope": 0,
           "!satisfy": 0,
           "!love": 0,
           "!stupidfox": 0,
           "!avatar": 0,
           "!fastfood": 0,
           "!entry": 2,
           "!msg": 2,
           "!users": 0,
           "!skip": 2,
           "!skiptro": 2,
           "!lockskip": 2,
           "!add": 2,
           "!remove": 2,
           "!move": 2,
           "!lock": 2,
           "!unlock": 2,
           "!kick": 2,
           "!ban": 2,
           "!unban": 2,
           "!giveaway start": 0,
           "!gstatus": 0,
           "!bl": 2,
           "!settings": 2,
           "!toggle ads": 2,
           "!toggle lottery": 2,
           "!toggle autowoot": 2,
           "!toggle timeguard": 2,
           "!toggle magnetic": 2,
           "!toggle welcome": 2,
           "!toggle history": 2,
           "!toggle urban": 2,
           "!toggle genreguard": 2,
           "!translate": 2,
           "!french": 2,
           "!spanish": 2,
           "!portuguese": 2,
           "!dutch": 2,
           "!mute": 2,
           "!unmute": 2,
           "!userid": 3,
           "!oldmute": 3,
           "!oldunmute": 3,
           "!clearchat": 3,
           "!msg": 3,
           "!troll": 3,
           "!clearwl": 3,
           "!motd": 3,
           "!motd clear": 3,
           "!motd off": 3,
           "!cooldown": 3,
           "!shutdown": 3,
           "!reload": 3,
           "!uptime": 3,
           "!status": 3,
           "!dropzone": 3,
           "!swap": 3,
           "!eval": 3


       }
  }
